name: rtgs-backend
type: web
env: python
buildCommand: pip install -r requirements.txt
startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
envVars:
  - key: PYTHON_VERSION
    value: "3.11.9"
  - key: SECRET_KEY
    value: rtgs-super-secret-key-2024-production-safe
  - key: DATABASE_URL
    value: sqlite:///./rtgs_automation.db
  - key: DEBUG
    value: "False"
  - key: CORS_ORIGINS
    value: '["*"]'